name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        name: setup node
        with:
          node-version: 18
      
      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform
        with: 
          terraform_version: 1.4.6
          
      - name: Terraform Init
        run: |
          terraform init -backend-config test-backend-config.tfvars -backend-config "access_key=${AWS_ACCESS_KEY_ID}"
          -backend-config "secret_key=${AWS_SECRET_ACCESS_KEY}"